"""`docs.*` rules over the listing, `doc_file`, `dependency` and `file_metrics` facts
(DOC-02..04)."""

from pydantic import Field

from archlens.globs import glob_match
from archlens.models import Evidence, Fact, RuleOutcome
from archlens.rubric.context import RuleContext
from archlens.rubric.registry import RuleParams, rule
from archlens.rubric.rules._common import (
    MAX_EVIDENCE,
    attr_bool,
    attr_int,
    attr_str,
    fact_evidence,
    missing_data,
    scan,
)
from archlens.rubric.rules.files import AnyExistsParams, any_exists

SPEC_GLOBS = ["**/{openapi,swagger}*.{yaml,yml,json}", "**/api-docs*.{yaml,yml,json}"]
AUTODOC_FRAMEWORKS = ("fastapi",)  # serve OpenAPI by default
AUTODOC_PACKAGES = (
    "swashbuckle", "springdoc", "@nestjs/swagger", "drf-spectacular", "drf-yasg", "flasgger",
    "flask-smorest", "apispec", "swagger-ui-express", "@fastify/swagger", "nswag",
)  # fmt: skip
ARCHITECTURE_GLOBS = [
    "docs/**/adr*/**", "docs/**/architecture*", "ARCHITECTURE*", "docs/**/decisions/**",
    "**/adr/**", "**/ADR-*",
]  # fmt: skip


class ApiSpecParams(RuleParams):
    globs: list[str] = Field(default_factory=lambda: list(SPEC_GLOBS))


def _autodoc_dependencies(ctx: RuleContext) -> list[Fact]:
    return [
        d for d in ctx.facts.by_kind("dependency")
        if any((attr_str(d, "name") or "").lower().startswith(p) for p in AUTODOC_PACKAGES)
        or (attr_str(d, "name") or "").lower() in AUTODOC_FRAMEWORKS
    ]  # fmt: skip


@rule("docs.api_spec")
def api_spec(ctx: RuleContext, params: ApiSpecParams) -> RuleOutcome:
    """An OpenAPI/Swagger file, or a framework/package that generates API docs."""
    specs = [f.path for f in ctx.files if glob_match(f.path, params.globs)]
    autodoc = sorted(set(ctx.profile.frameworks) & set(AUTODOC_FRAMEWORKS))
    deps = _autodoc_dependencies(ctx)
    query = "OpenAPI/Swagger files or doc-generating frameworks"
    evidence: list[Evidence] = [scan(ctx, "files", query, len(specs) + len(autodoc) + len(deps))]
    evidence += [e for p in specs[:5] if (e := ctx.evidence(p, 1)) is not None]
    evidence += fact_evidence(deps, MAX_EVIDENCE - len(evidence))
    if specs:
        return RuleOutcome(
            verdict="pass", claim=f"API spec: {', '.join(specs[:3])}.", evidence=evidence
        )
    if autodoc or deps:
        names = autodoc + sorted({attr_str(d, "name") or "?" for d in deps})
        return RuleOutcome(
            verdict="pass",
            claim=f"API docs are generated by {', '.join(dict.fromkeys(names))}.",
            evidence=evidence,
        )
    return RuleOutcome(
        verdict="fail", claim="No OpenAPI/Swagger spec and no doc-generating framework.",
        evidence=evidence,
    )  # fmt: skip


class ArchitectureParams(RuleParams):
    globs: list[str] = Field(default_factory=lambda: list(ARCHITECTURE_GLOBS), min_length=1)


@rule("docs.architecture")
def architecture(ctx: RuleContext, params: ArchitectureParams) -> RuleOutcome:
    """pass if any architecture document or ADR exists, else fail."""
    outcome = any_exists(ctx, AnyExistsParams(globs=params.globs))
    if outcome.verdict == "fail":
        return outcome.model_copy(update={"claim": "No architecture documents or ADRs found."})
    return outcome


class DocstringParams(RuleParams):
    pass_at: float = 0.6
    partial_at: float = 0.3


@rule("docs.docstring_ratio")
def docstring_ratio(ctx: RuleContext, params: DocstringParams) -> RuleOutcome:
    """Σ documented / Σ public functions over non-test, non-generated files; NA without any."""
    if (missing := missing_data(ctx, "ast:metrics")) is not None:
        return missing
    files = [
        f for f in ctx.facts.by_kind("file_metrics")
        if not attr_bool(f, "is_test") and not attr_bool(f, "is_generated")
    ]  # fmt: skip
    public = sum(attr_int(f, "public_functions") for f in files)
    documented = sum(attr_int(f, "documented_functions") for f in files)
    query = f"documented {documented} / public {public} functions"
    if public == 0:
        return RuleOutcome(
            verdict="not_applicable", claim="No public functions were found.",
            evidence=[scan(ctx, "ast:metrics", query, 0)], reason="no_public_functions",
        )  # fmt: skip
    share = documented / public
    verdict = (
        "pass" if share >= params.pass_at else "partial" if share >= params.partial_at else "fail"
    )
    return RuleOutcome(
        verdict=verdict,
        claim=f"{documented} of {public} public functions ({share:.0%}) have docstrings or "
        "doc comments.",
        evidence=[scan(ctx, "ast:metrics", query, documented)],
    )
