import pytest

from archlens.ingest.filters import (
    count_loc,
    detect_language,
    is_binary,
    is_generated,
    is_vendored,
)


@pytest.mark.parametrize(
    ("path", "language"),
    [
        ("app/main.py", "python"),
        ("web/App.tsx", "typescript"),
        ("src/Program.cs", "csharp"),
        ("Dockerfile", "dockerfile"),
        ("deploy/api.Dockerfile", "dockerfile"),
        ("Dockerfile.prod", "dockerfile"),
        ("Makefile", "make"),
        (".github/workflows/ci.yml", "yaml"),
        ("infra/main.bicep", "bicep"),
        ("LICENSE", None),
    ],
)
def test_detect_language(path: str, language: str | None) -> None:
    assert detect_language(path) == language


@pytest.mark.parametrize(
    ("path", "expected"),
    [
        ("node_modules/left-pad/index.js", True),
        ("web/node_modules/x/y.js", True),
        ("vendor/github.com/x/y.go", True),
        (".venv/lib/site.py", True),
        ("src/vendored_helpers.py", False),
        ("vendor.py", False),
    ],
)
def test_is_vendored(path: str, expected: bool) -> None:
    assert is_vendored(path) is expected


@pytest.mark.parametrize(
    ("path", "head", "expected"),
    [
        ("static/app.min.js", b"", True),
        ("dist/bundle.js", b"", True),
        ("package-lock.json", b"{}", True),
        ("uv.lock", b"", True),
        ("api/pb/user_pb2.py", b"", True),
        ("internal/gen.go", b"// Code generated by protoc-gen-go. DO NOT EDIT.\n", True),
        ("src/x.ts", b"/* @generated by openapi */", True),
        ("app/main.py", b"import os\n", False),
        ("docs/building.md", b"", False),
    ],
)
def test_is_generated(path: str, head: bytes, expected: bool) -> None:
    assert is_generated(path, head) is expected


def test_is_binary_uses_nul_in_first_8k() -> None:
    assert is_binary(b"\x89PNG\r\n\x1a\n\0\0")
    assert not is_binary("ünïcödé text\n".encode())
    assert not is_binary(b"a" * 9000 + b"\0")  # NUL beyond the sniff window


def test_count_loc_skips_blank_lines() -> None:
    assert count_loc(b"a\n\n  \nb\r\nc") == 3
    assert count_loc(b"") == 0
